cask 'font-sanfrancisco' do
  version :latest
  sha256 '362217cca45425fe1e86307cc690f78fa84289ee2e11e71fb6c49d54c13b8017'

  # devimages-cdn.apple.com was verified as official when first introduced to the cask
  url 'https://devimages-cdn.apple.com/design/downloads/SF-Font.dmg'
  name 'San Francisco'
  homepage 'https://developer.apple.com/fonts/'

  font 'SF Compact/SFCompactDisplay-Black.otf'
  font 'SF Compact/SFCompactDisplay-Bold.otf'
  font 'SF Compact/SFCompactDisplay-Heavy.otf'
  font 'SF Compact/SFCompactDisplay-Light.otf'
  font 'SF Compact/SFCompactDisplay-Medium.otf'
  font 'SF Compact/SFCompactDisplay-Regular.otf'
  font 'SF Compact/SFCompactDisplay-Semibold.otf'
  font 'SF Compact/SFCompactDisplay-Thin.otf'
  font 'SF Compact/SFCompactDisplay-Ultralight.otf'
  font 'SF Compact/SFCompactText-Bold.otf'
  font 'SF Compact/SFCompactText-BoldItalic.otf'
  font 'SF Compact/SFCompactText-Heavy.otf'
  font 'SF Compact/SFCompactText-HeavyItalic.otf'
  font 'SF Compact/SFCompactText-Light.otf'
  font 'SF Compact/SFCompactText-LightItalic.otf'
  font 'SF Compact/SFCompactText-Medium.otf'
  font 'SF Compact/SFCompactText-MediumItalic.otf'
  font 'SF Compact/SFCompactText-Regular.otf'
  font 'SF Compact/SFCompactText-RegularItalic.otf'
  font 'SF Compact/SFCompactText-Semibold.otf'
  font 'SF Compact/SFCompactText-SemiboldItalic.otf'
  font 'SF Pro/SF-Pro-Display-Black.otf'
  font 'SF Pro/SF-Pro-Display-BlackItalic.otf'
  font 'SF Pro/SF-Pro-Display-Bold.otf'
  font 'SF Pro/SF-Pro-Display-BoldItalic.otf'
  font 'SF Pro/SF-Pro-Display-Heavy.otf'
  font 'SF Pro/SF-Pro-Display-HeavyItalic.otf'
  font 'SF Pro/SF-Pro-Display-Light.otf'
  font 'SF Pro/SF-Pro-Display-LightItalic.otf'
  font 'SF Pro/SF-Pro-Display-Medium.otf'
  font 'SF Pro/SF-Pro-Display-MediumItalic.otf'
  font 'SF Pro/SF-Pro-Display-Regular.otf'
  font 'SF Pro/SF-Pro-Display-RegularItalic.otf'
  font 'SF Pro/SF-Pro-Display-Semibold.otf'
  font 'SF Pro/SF-Pro-Display-SemiboldItalic.otf'
  font 'SF Pro/SF-Pro-Display-Thin.otf'
  font 'SF Pro/SF-Pro-Display-ThinItalic.otf'
  font 'SF Pro/SF-Pro-Display-Ultralight.otf'
  font 'SF Pro/SF-Pro-Display-UltralightItalic.otf'
  font 'SF Pro/SF-Pro-Text-Bold.otf'
  font 'SF Pro/SF-Pro-Text-BoldItalic.otf'
  font 'SF Pro/SF-Pro-Text-Heavy.otf'
  font 'SF Pro/SF-Pro-Text-HeavyItalic.otf'
  font 'SF Pro/SF-Pro-Text-Light.otf'
  font 'SF Pro/SF-Pro-Text-LightItalic.otf'
  font 'SF Pro/SF-Pro-Text-Medium.otf'
  font 'SF Pro/SF-Pro-Text-MediumItalic.otf'
  font 'SF Pro/SF-Pro-Text-Regular.otf'
  font 'SF Pro/SF-Pro-Text-RegularItalic.otf'
  font 'SF Pro/SF-Pro-Text-Semibold.otf'
  font 'SF Pro/SF-Pro-Text-SemiboldItalic.otf'

end
